### PR TITLE
[16][ADD] attachment_asset_in_db (from ak incubator)

### PR DESCRIPTION
**Pull request by florian-dacosta**

### CODE REVIEW

**Comment by florian-dacosta** [comment]
I am not sure why pre-commit want to remove all content of `__init__` files...

**Comment by hparfr** [comment]
yes; do not know
i've updated 16.0 few minutes ago; but stil the same issues with __init__
and it force changes in website key too

**Comment by florian-dacosta** [comment]
Shouldn't we have something similar to https://github.com/OCA/oca-addons-repo-template/blob/master/.pre-commit-config.yaml ?

**Comment by hparfr** [comment]
yes it is

**Pull request merged**
